spring:
  application:
    name: Homework18-Spring_RestAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/Module18-Database
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security: debug
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui.html
jwt:
  secret: 8b2e9fe731e9384f9cfc98290f8272b0df7e73e87c6a0d8c5ff4c3d7c27f1f7b
  expiration: 3600000
